alexa/ask-toolkit-for-vscode

- snippets/lambdaSDKPythonSnippet.json
> At the Request Snippet, the placeholder was Intent instead of Request

- README.md
- package.json
- src/commands/external/contactAlexaTeam.ts
- src/commands/external/openDeveloperPortal.ts
- src/commands/external/openHelpDoc.ts
- src/utils/askCliHelper.ts
- src/utils/commandParametersHelper.ts
- src/utils/commandRunner.ts
- src/utils/lowLevelCommandBuilder.ts
- src/utils/profileManager.ts
- src/utils/statusBarHelper.ts
Since [opn](https://www.npmjs.com/package/opn) module is deprecated, replacing it with [open](https://www.npmjs.com/package/open). 
Also corrected minor spell mistakes.
> Replaced opn npm module with open because of deprecation

- README.md
- package.json
- src/utils/askCliHelper.ts
- src/utils/configuration.ts
- src/utils/profileManager.ts
Since CLI released a major version [v2.0.1](https://www.npmjs.com/package/ask-cli) recently. 
VSCode still depends on CLI v1 major build to execute commands so updating the errorMessage to instruct on installing CLI v1 version.
*Screenshot:*
> Update code/docs to specify usage of CLI v1 version

- package.json
- src/runtime/lib/utils/constants.ts
- src/runtime/lib/utils/profileHelper.ts
**Description**
This commit contains the following changes:
- The profile configuration file was created on [default permissions](https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback)
(`0666`) which had more access than needed. Changed it to only have
read write permissions for current user (`0600`), for more secure
access.
- Moved some hard coded strings in profile helper, to constants file
and reformated profile helper.
- Changed extension run script to compile before doing webpack.
**Testing**
- Tested by moving the existing profile file and restarting the extension to go through the sign in process again and checked the newly created profile file permissions.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> Change permissions on profile config file

- src/askContainer/commands/cloneSkillFromConsole.ts
- src/askContainer/treeViews/treeViewProviders/helpViewProvider.ts
- src/askContainer/treeViews/treeViewProviders/skillActionsViewProvider.ts
- src/extension.ts
- src/runtime/lib/API.ts
- src/runtime/lib/smapiClientFactory.ts
- src/utils/cloneSkillHelper.ts
- src/utils/urlHandlers.ts
**Description**
This commit introduces the following changes :
- A new cloneSkillFromConsole command which handles cloning the hosted skills
from developer console.
- Reformatting common logic from cloneSkill and cloneSkillFromConsole command
to a new utility function.
- Setting the user agent specific to extension for SMAPI SDK initialization.
- Setting correct telemetry command names for open URL commands.
**Testing**
- Tested with cloning skill directly and from console, to see that the new process is triggered and skills cloning works.
> feat: Add telemetry for hosted skills clone, open URLs, and SMAPI user agent

- package.json
- src/extension.ts
- test/runTest.ts
1. The current testRunner script is failing
2. There are lot lint issues need to be fixed, thus temporarily remove lint task in pretest.
3. Revert some await before Thenable return type
> fix: fix testRunner script and revert some await usage

- README.md
Due to this [issue](https://github.com/alexa/ask-toolkit-for-vscode/issues/39), Add one more FAQ to explain the reason why the user get a prompt for Git credentials when an Alexa host skill is created or downloaded with Git version 2.26.x or 2.25.x
> Added defect git version issue into FQA

- package-lock.json
Due to current security alert
Update yargs-parser version to 18.1.2 based on security recommendation
> fix: upgrade yargs-parser version in package-lock.json

- src/askContainer/commands/simulateReplay.ts
- src/askContainer/commands/simulateSkill.ts
- src/askContainer/webViews/simulateSkillWebview.ts
- src/utils/simulateMessageHelper.ts
- src/utils/simulateNonSkillHelper.ts
- src/utils/simulateReplayHelper.ts
- src/utils/simulateSkillHelper.ts
*Issue #, if available:* 
With the growing features, the `simulatSkillHelper` file is getting larger, which will be difficult to maintain and do unit test.
This PR separates the `simulateSkillHelper` file into three smaller files -`simulateSkillHelper`,`simulateNonSkillHelper` and `simulateMessageHelper`, which would be more clear than before.
> Improve simulateSkillHelper file into three smaller helper files

- .versionrc.json
- package-lock.json
- package.json
- Add `standard-version` for automating release process of the extension, now that commit lint has been added.
- Add `vsce` as npm script for easier release automation process.
> chore: add standard version for auto changelog, version bump

- src/utils/gitHelper.ts
*Issue*
Failed to assign git execution current working directory, which causes skill clone failing.
*Test*
Test skill creation/ skill clone and skill development.
> fix: missing git execution current working directory

- package-lock.json
- package.json
- src/askContainer/commands/viewAllSkills.ts
- test/testUtilities.ts
- VSCode extension API changed the icon path behavior for QuickInputButton API, and is asking for Uri instead of file path. Updated the icon path to fix that. Without this change, toolkit users on VSCode 1.51.1 version will not be able to use `Download skill` feature.
- Updated globalStorage fake object in tests with the correct type structure.
- Updated package-lock.json to reflect the new vscode library dependency use
- Was able to use `Download skill` button after the changes.
- `npm tests` run as expected.
> fix: iconpath for quick input button for vscode 1.51.1, update package lock and tests for new version

- media/previewApl/aplRenderUtils.js
APL 1.3 and above allows parameters to use key names other than `payload` as mentioned in the `About binding a data source to payload or other parameters` section [here](https://developer.amazon.com/en-US/docs/alexa/alexa-presentation-language/apl-data-source.html#bind-the-data-source-to-the-document). When using a document that has custom named parameters, the APL previewer doesn't render the doc because it is only using the first parameter. This PR fixes that, by taking all parameters into consideration.
*document.json*
```json
{
"type": "APL",
"version": "1.3",
"settings": {},
"theme": "dark",
"import": [
{
"name": "alexa-layouts",
"version": "1.1.0"
}
],
"resources": [],
"styles": {
"bigText": {
"values": [
{
"fontSize": "72dp",
"textAlign": "center"
}
]
}
},
"onMount": [], …
```
> Fix AplRenderUtils, to use all parameters in APL document during APL preview

- .github/workflows/extensionTests.yml
- test/extension.test.ts
- test/index.ts
- test/runtime/utils/profileHelper.test.ts
This PR adds the extension tests as github actions, following the vscode extension CI docs : https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions. The PR also fixes some extension source that used to fail on windows machines.
Created a PR on `development` branch in own fork here, to run the github actions : https://github.com/nikhilym/ask-toolkit-for-vscode/pull/1 . You can check the github actions run history here : https://github.com/nikhilym/ask-toolkit-for-vscode/actions/runs/384406638
> Add github actions to run extension tests on PRs/ pushes

- media/previewApl/aplRenderUtils.js
This commit adds the else condition to the apl content builder, for parameter names that are missing in the datasources document. This is done w.r.t the changes suggested by APL team : https://github.com/alexa/ask-toolkit-for-vscode/pull/68#pullrequestreview-538039520 . @alexa/alexa-multimodal team / @renewu0707 can review the changes too.
> fix: add condition to apl renderer content for invalid parameter names

- .github/workflows/stale.yml
This PR fixes the [stale workflow bot](https://github.com/alexa/ask-toolkit-for-vscode/blob/development/.github/workflows/stale.yml) that incorrectly sets the issues with correct labels like `feature request`, `external dependency waiting` to `stale`. The workflow actions on #38 lead to making this fix.
> chore: update stale bot configuration

- package.json
configure current working directory to skill code folder. Defaults to the lambda skill package structure.
*Issue #, if available:* https://github.com/alexa/alexa-skills-kit-sdk-for-python/issues/183
> fix: configure current working directory to skill code folder

- media/previewApl/previewApl.html
- package-lock.json
- package.json
Feature
- upgrade apl-suggester dependency from 1.1.1 to 1.5
- upgrade apl-viewhost-web dependency from 1.4.0 to 1.5
- update reference link of apl web view host from 1.4 to 1.5 in previewApl HTML
> feat: upgrade apl-suggester and apl-viewhost-web to version 1.5

- media/simulateSkill/simulateSkill.js
**Description of changes:**
This PR fixes the issue of not rendering APL responses, in case there is an empty speak tag in Alexa response, but valid APL response. This fixes the issue mentioned in #82 
> fix: render apl response without speak tag in simulator. fixes #82

- package.json
To pass an argument from npm run script to vsce package. e.g. We can set the $npm_config_out configuration parameter to --out . An environment parameter that starts with npm_config_ will be interpreted as a configuration parameter (See doc (https://docs.npmjs.com/cli/v6/using-npm/config#environment-variables)). 
> fix: passing command line arguments to npm script in package.json

- test/utils/commands/openUrl.test.ts
- test/utils/commands/openWorkspace.test.ts
**Description of changes:**
- Due to the [recent vscode change](https://github.com/microsoft/vscode/commit/3ba967fd7eb97621b0e2a4fb0267b70323ffcf5f), errors raised by the extension are logged onto the extension host output window and a generic error message `Running the contributed command: <> failed.` is thrown. This leads to the unit test failures as can be checked [here](https://github.com/alexa/ask-toolkit-for-vscode/pull/95/checks?check_run_id=1841683081) 
- This PR fixes the issue, by changing the error message to be asserted.
- Tested the error messages thrown to the user are working as expected in the extension between vscode 1.52.1 and vscode 1.53. Also tested that the above mentioned commit is responsible for this change, by downgrading to the earlier version and running `npm …
> Fix the unit tests failing in the extension due to VSCode 1.53 version

- src/aplContainer/commands/createAplDocumentFromSample.ts
Some unused APL sample templates will break create APL template from sample template dropdown. This filter removed unused sample templates to fix the issue. The unused APL templates are for testing purpose
> fix: filter unused APL sample templates

- media/previewApl/aplRenderUtils.js
- media/simulateSkill/simulateSkill.html
- src/askContainer/commands/simulateSkill.ts
- src/askContainer/webViews/simulateSkillWebview.ts
- src/runtime/lib/API.ts
- test/utils/commands/openUrl.test.ts
- test/utils/commands/openWorkspace.test.ts
- bug1: The simulator apl preview can't be totally rendered after switching between webviews. The reason maybe VSC webview has limited storage or webview handled something when switch webview.
- bug2: The simulator failes to render apl preview if the datasource is empty.
- For bug1: use retainContextWhenHidden to keep the webview persist.
- For bug2: setup dataSource to '{}' if it's empty.
- Nit change: update apl version to 1.5 in `simulateSkill.html`.
> fix: bugs of simulate APL preview

- media/previewApl/aplRenderUtils.js
- media/simulateSkill/simulateSkill.js
- src/utils/simulateSkillHelper.ts
The toolkit simulator supports Alexa.Presentation.APL.RenderDocument directive, but not Alexa.Presentation.APL.ExecuteCommands directive. Related feature request: https://github.com/alexa/ask-toolkit-for-vscode/issues/67
Change: catch ExecuteCommands directive from SMAPI response, then render it in APL preview.
> feat: support APL ExecuteCommands directive in toolkit simulator

- src/askContainer/commands/listSkills.ts
- src/askContainer/commands/viewAllSkills.ts
- test/askContainer/commands/listSkills.test.ts
- tsconfig.json
- This PR fixes the issue of showing only the latest custom skills that come under the first 50 skills that [`listSkills` API](https://developer.amazon.com/en-US/docs/alexa/smapi/skill-operations.html#list-skills) responds with, by doing multiple `listSkills` calls when there are more skills available to check.
- The PR also fixes the performance issue due to the thread sleep method that was introduced to remove [API throttling for `getHostedSkillMetadata` API](https://github.com/alexa/ask-toolkit-for-vscode/blob/development/src/askContainer/commands/viewAllSkills.ts#L48-L49), by using the `async-retry` library and using reasonable retry options. 
- Since `getHostedSkillMetadata` raises an exception if the skill is not a hosted skill, and an exception when the API is throttled, to …
> Fix to list all custom skills under 'download skills' quick pick

- src/askContainer/webViews/deploySkillWebview/deployHostedSkillWebview.ts
- src/askContainer/webViews/deploySkillWebview/deployNonHostedSkillWebview.ts
- src/askContainer/webViews/welcomeScreenWebview.ts
1. The deploy status overview table in the skill deploy webview is not loading when first reveal in 1.53.2 v
2. The blog and feature info in the welcome screen webview is not updated when first reveal in 1.53.2 v
1. Call `refresh` method in `getHtmlForView` method whenever the deploy skill webview is generated.
2. Call `getBlogUpdates` and `getFeatureUpdates` in `getHtmlForView` method whenever the welcome webview is generated.
In the visual studio code 1.52.1 version, the `webviewPanel.onDidChangeViewState` is fired when first showing a webview. However, it does not work in 1.53.2 version. 
Post a question with `visual-studio-code` tag in stackflow : https://stackoverflow.com/questions/66426238/is-webviewpanel-ondidchangeviewstate-not-fired-when-first-showing-a-webview-in-t
1. Open the …
> fix: deploy status overview is not loading in 1.53.2 V

- src/askContainer/webViews/deploySkillWebview/deployHostedSkillWebview.ts
- src/askContainer/webViews/deploySkillWebview/deployNonHostedSkillWebview.ts
- src/constants.ts
To consolidate hosted skill and self hosted skill deploy webviews messages in the constants file
To consolidate the messages for better readability and easy maintainance.
The skill deploy status overview table shows the expected messages.
> fix: consolidate deploy webviews messages in the constants file

- media/createSkill/createSkill.html
This change allows the usage of Node.js 12 for Alexa Hosted Skills creation.
This change has been tested.
> feat: set node.js 12 as default hosted skill node.js runtime version

- media/previewApl/previewApl.html
- package.json
Feature
- upgrade apl-suggester dependency from 1.7.0 to 1.8.0;
- upgrade apl-viewhost-web dependency from 1.7.0 to 1.8.0;
- update reference link of apl webview host from 1.7 to 1.8 in `previewApl.html`
> feat: upgrade apl-suggester and apl-viewhost-web to version 1.8

- test/askContainer/webview/deploySkillWebview.test.ts
- test/utils/commands/openUrl.test.ts
- test/utils/commands/openWorkspace.test.ts
- fix: skipping broken tests to unblock extension patch release
- We need to do a patch release of the extension on renaming the client secret constants.
- npm run test success
> fix: skipping broken tests to unblock extension patch release

- media/previewApl/previewApl.html
- package.json
Upgrade apl-suggester and apl-viewhost-web to version 1.9
Upgrade apl-suggester and apl-viewhost-web to version 1.9
Test locally by running ```npm install``` and Run and Debug the extension for APL related features.
> feat: upgrade apl-suggester and apl-viewhost-web to version 1.9

- media/previewApl/previewApl.html
- package-lock.json
- package.json
Upgrade apl-suggester and apl-viewhost-web to version 2022.1
Test locally by running `npm i` and then running and debugging the extension for APL related features.
> feat: upgrade apl-suggester and apl-viewhost-web to version 2022.1

- src/runtime/lib/utils/lwa.ts
- src/utils/captchaValidator.ts
reverting PR that changed 127.0.0.1 usage to localhost
These changes are causing an issue with LWA, preventing new users from logging into and using the extension. We are working on a permanent fix and intend to re-introduce the changes when the LWA configurations are updated and more thoroughly vetted.
Related issues:
https://github.com/alexa/ask-toolkit-for-vscode/issues/192
https://github.com/alexa/ask-toolkit-for-vscode/issues/191
Manual testing against the LWA portal:
- Opened profile manager in the extension (3 small dots next to the Skills Management sidebar)
- Entered 'abc' in the Enter profile name under Create new profile, and hit Create
- Redirected to the browser, verified 127.0.0.1 is in the url rather than localhost, verified that login was successful
Unit tests:
> fix: revert pull request #164 causing authentication failures

- src/runtime/lib/utils/lwa.ts
- src/utils/captchaValidator.ts
Use localhost instead 127.0.0.1 for WSL support
Re-introducing the changes to use localhost in the redirect URL for LWA authentication, rather than 127.0.0.1.
The changes were initially introduced [here](https://github.com/alexa/ask-toolkit-for-vscode/pull/164) and reverted [here](https://github.com/alexa/ask-toolkit-for-vscode/pull/193).
This allows the redirect to go through successfully for WSL users.
For context, these changes were introduced in version 2.11.2 of the extension but were backed out, as it caused an issue for new profiles when attempting to authenticate. The redirect URL whitelist in the existing security profile was not configured to allow for localhost:9090. We have since updated the configuration and can move ahead with this change (testing details below). 
Downgraded …
> fix: use localhost instead of 127.0.0.1 for LWA redirect

- test/runTest.ts
VSCode update in 1.73.1 broke some of the WebView loading behavior in our test utilities, rolling back for 1.72.2 temporarily until the root cause is resolved.
All unit tests pass.
> fix: rolling back VSCode version for testing to 1.72.2

- src/runtime/lib/API.ts
- test/askContainer/commands/deviceRegistry.test.ts
Context menu commands do not work.
fixes #227 that has been bizarrely closed in favour of a workaround.
https://github.com/tonyhallett/ask-toolkit-for-vscode/blob/fix-closed-issue-227/test/askContainer/commands/deviceRegistry.test.ts
> fix: correct AbstractCommand for context menus

- media/previewApl/previewApl.html
- package-lock.json
- package.json
Upgrade apl-suggester and apl-viewhost-web to version 2023.1
This PR updates VS Code Extension to use the latest version of suggester and viewhost.
Test locally by running npm i and then running and debugging the extension for APL related features.
> feat: upgrade apl-suggester and apl-viewhost-web to version 2023.1

- media/createSkill/createSkill.html
This change is to update Alexa Hosted Skills node runtime to Node.js 16.
> feat: setting Node.js 16 as default runtime for AlexaHosted Skills
