alexa/ask-toolkit-for-vscode

CHANGELOG.md
package.json
snippets/askSnippets.json
src/commands/highLevelCommands/dialog.ts
src/commands/lowLevelCommands/add-beta-testers.ts
src/commands/lowLevelCommands/associate-catalog-with-skill.ts
src/commands/lowLevelCommands/create-beta-test.ts
src/commands/lowLevelCommands/create-catalog.ts
src/commands/lowLevelCommands/end-beta-test.ts
src/commands/lowLevelCommands/get-beta-test.ts
src/commands/lowLevelCommands/get-catalog-upload.ts
src/commands/lowLevelCommands/get-catalog.ts
src/commands/lowLevelCommands/list-beta-testers.ts
src/commands/lowLevelCommands/list-catalog-uploads.ts
src/commands/lowLevelCommands/list-catalogs.ts
src/commands/lowLevelCommands/remove-beta-testers.ts
src/commands/lowLevelCommands/request-feedback-from-beta-testers.ts
src/commands/lowLevelCommands/send-reminder-to-beta-testers.ts
src/commands/lowLevelCommands/start-beta-test.ts
src/commands/lowLevelCommands/update-beta-test.ts
src/commands/lowLevelCommands/upload-catalog.ts
src/commands/lowLevelCommandsRegister..ts
src/extension.ts
src/utils/basicCommandInputParameters.ts
src/utils/configuration.ts

1. Support one high level command: ask dialog.
2. Support some low level commands in beta-test and catalog category.
3. Add a new snippet for a new AMAZON built-in intent: SelectIntent.

Support several new commands and changes in ASK CLI

---

CHANGELOG.md
package.json

Release v1.0.2, update CHANGELOG and package version.

---

CHANGELOG.md
package.json

Release v1.0.3, update CHANGELOG and package version.

Release v1.0.3, update CHANGELOG and package version.

---

README.md

Add two FAQs on README:
1. How do I start Alexa Skills Kit Toolkit over SSH remote development?
2. What if I failed to sign in Amazon account over SSH remote development?

Add two FAQs on README

---

.vscode/launch.json
README.md
package.json
test/extension.test.ts
test/index.ts

The activate extension test is failing 
Fix the activate extension unit test
Yes

fix: fix the activate extension test

---

.eslintrc.js
src/askContainer/treeViews/skillConsoleView.ts
src/askContainer/treeViews/treeViewProviders/skillActionsViewProvider.ts
src/askContainer/webViews/interactionModelSync.ts
src/askContainer/webViews/manifestSync.ts
src/askContainer/webViews/profileManagerWebview.ts
src/constants.ts
src/exceptions.ts
src/extension.ts
src/runtime/lib/API.ts

there's some lint issues based on the current lint rules
Fix some lint issues, will continue to fix the rest.

fix: fix some lint issues

---

package.json

Update apl-suggester version to 1.1.1

Update apl-suggester version

---

media/createSkill/createSkill.html
media/interactionModelSync/interactionModelSync.html
media/simulateSkill/simulateSkill.js

*Issue #, if available:* None
*Description of changes:* Fix Portugese (BR) to Portuguese (BR)

Fix: Portugese (BR) to Portuguese (BR)

---

.commitlintrc.json
CONTRIBUTING.md
package.json

- Add contribution guidelines with branch organization details.
- Add pre-commit hooks and conventional commit configuration.

chore: add contribution guidelines and pre-commit hooks

---

package.json

Updating the configuration snippet to add a region param that is set to NA(the default value). The users are expected to refer to the setup steps [here](https://developer.amazon.com/en-US/docs/alexa/ask-toolkit/vs-code-testing-simulator.html) and provide the region(EU, FE or NA).

feat: update debug configuration snippet in package.json with a choice region input

---

media/createSkill/createSkill.html
media/createSkill/createSkill.js
src/askContainer/webViews/createSkillWebview.ts
src/utils/createSkillHelper.ts

- Add default AWS region configuration for Alexa-hosted skills creation webview.

feat: add default aws region for create hosted skill

---

.github/workflows/stale.yml

Updating the stale actions version to V3

chore: update stale bot configuration

---

languages/acdl/language-configuration.json
languages/acdl/syntaxes/acdl.tmLanguage.json
package-lock.json
package.json
test/acdlSyntaxHighlighterGrammar.test.ts

This PR adds the ACDL Syntax Highlighter grammar configurations to the toolkit
- Beta release of ACDL and compatibility with ACDL skills.
- Test ACDL files to be having syntax highlighting from the extension
- Test old and new test cases being passed

feat: acdl syntax highlighter

---

src/askContainer/commands/viewAllSkills.ts
src/utils/skillHelper.ts

*Issue:*
The list of skills are not updated in realtime so users may clone a skill that does not exist remotely. 
Failure message:
`Skill clone failed. Reason: Git folder setup failed for ${folder directory}. Reason: The resource being requested is not found.`
1. Add a timer to update the list of skills periodically.
2. Check if a skill exists before downloading it.
3. New error message : `The skill '${skillName}' was not found. Please check if the skill exists in the Alexa developer console` 
4. To automatically refresh the list whenever the requested skill is not found.

fix: 'resource not found' when cloning a skill

---

media/previewApl/previewApl.html
package-lock.json
package.json
src/aplContainer/config/configuration.ts

Upgrade the version from 1.5 to 1.6 with APL suggester 
Upgrade the version from 1.5 to 1.6 hotfix with APL WebViewhost
Add more sample templates' mapping to vs code filter. 
npm install locally and include the new package lock json. 
Upgrade APL version to the latest version.
NPM build tests
Manual E2E tests with sample APL skill. Details can be found in the internal Quip Doc.
- [ X ] New feature (non-breaking change which adds functionality)
- [ X ] My code follows the code style of this project
- [ X ] I have read the **README** document
- [ X ] All new and existing tests passed
- [ X ] My commit message follows [Conventional Commit Guideline](https://conventionalcommits.org/)
- [ X ] By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

Upgrade APL 1.5 to 1.6 with APL Web Viewhost and APL Suggester.

---

package-lock.json
package.json

Fixing the security vulnerability w.r.t CVE https://github.com/advisories/GHSA-cf4h-3jhx-xvhq on the toolkit repository, by updating the dependencies `vsce` and `typed-rest-client` packages to the latest ones, that has their `underscore` package fixed.
- For `vsce` check, tested if the package build is working as expected.
- For `typed-rest-client`, check that the skill package helper functions are working as expected.

chore: update vsce, typed-rest-client to fix security cve 

---

package-lock.json
test/testUtilities.ts

Updated package-lock.json to update trim-lines  minimum version to address the [security bug](https://github.com/alexa/ask-toolkit-for-vscode/security/dependabot/package-lock.json/trim-newlines/closed)

fix: update package-lock.json to update trim-lines security patch

---

media/toolkitUpdate/toolkitUpdate.html

chore: updates for next release

---

media/toolkitUpdate/toolkitUpdate.html

update the update html page for next release

chore: update for next release

---

src/runtime/lib/utils/lwa.ts
src/utils/captchaValidator.ts

Windows Subsystem for Linux is a compatibility layer for running Linux binary executables natively on Windows 10, Windows 11, and Windows Server 2019.
Fix https://github.com/alexa/ask-toolkit-for-vscode/issues/163
I tested it just changing to localhost in the web browser URL bar and it works.
Well I can show the screenshots of the 404 error status with 127.0.0.1

Use localhost instead 127.0.0.1 for WSL support

---

README.md

Adding FAQ section concerning the issue/workaround described here - https://github.com/alexa/ask-toolkit-for-vscode/issues/186
To facilitate discoverability of the workaround, and give a single place to point users to if they encounter this issue.
Documentation only.

chore: add section in FAQ for access token error+workaround

---

media/previewApl/previewApl.html
package-lock.json
package.json

Upgrade apl-suggester and apl-viewhost-web to version 2022.2
Test locally by running npm i and then running and debugging the extension for APL related features.

feat: upgrade apl-suggester and apl-viewhost-web to version 2022.2

---

CHANGELOG.md
package-lock.json
package.json

plan is to bump up the version then merge to the master for publishing to vscode marketplace. 
ran: 
```
npm run pre-release -- --release-as minor
```
N/A  = [X] release chore
- [0] My change requires a change to the documentation
- [)] I have updated the documentation accordingly

chore(release): 2.12.0

---

.github/workflows/release.yml

In order to simplify the release process, we are creating a github workflow action that will be run when commits are pushed to the master branch. This will leverage the [vsce-publish-action](https://github.com/sigma/vsce-publish-action) action, and automatically publish the new changes pushed to ```master``` branch to the VSCE marketplace. 
tested the latest changes using a feature branch and was able to release Version 2.12.0 of the [ASK Toolkit](https://marketplace.visualstudio.com/items?itemName=ask-toolkit.alexa-skills-kit-toolkit&ssr=false#version-history)
- [0] I have added tests to cover my changes

Mdoiron workflows

---

CHANGELOG.md
media/toolkitUpdate/toolkitUpdate.html
package-lock.json
package.json

Release ASK Toolkit 2.13.0

---

README.md

chore: remove SVG badges temporarily

---

package-lock.json
package.json

chore: release 2.13.1

---

package-lock.json
package.json

synchronizing master with development

---

package-lock.json
package.json

synchronize master and development

---

.gitignore
CHANGELOG.md
CONTRIBUTING.md
package-lock.json
package.json

Node16 release 2.14.0

---

.gitignore
CHANGELOG.md
CONTRIBUTING.md
media/createSkill/createSkill.html
package-lock.json
package.json

Releasing 2.14.0 of the ASK Toolkit. See CHANGELOG.md for changes.

Release 2.14.0
